---
- name: Make sure targets are deployed
  ansible.builtin.lineinfile:
    path: '{{ (
           item.path_prefix if item.path_prefix is defined else
           (prometheus_target_exporter_defaults[item.id].path_prefix
           | default(prometheus_target_exporter_target_prefix))
           if item.id is defined)
           ~
           (item.path if item.path is defined
           else prometheus_target_exporter_defaults[item.id].path if item.id is defined) | mandatory }}'
    line: '{{ prometheus_target_strategy_lineinfile_prefix ~
           (item.host if item.host is defined else prometheus_target_exporter_defaults[item.id].host) | mandatory ~
           prometheus_target_strategy_lineinfile_suffix }}'
    state: present
  become: true
  delegate_to: '{{ prometheus_target_host }}'
  loop: '{{ prometheus_target_exporter +
         ([] if prometheus_target_skip_default_exporters else prometheus_target_default_exporters) }}'
  notify:
    - Run command hook
    - Run shell hook
