FROM {{ item.image }}

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       sudo wget \
       python3-pip python3-dev python3-setuptools python3-wheel python3-apt \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean

ENTRYPOINT ["bash", "-c", "sleep infinity"]
